// <auto-generated />
using System;
using HarmonIQ.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HarmonIQ.Api.Persistence.Migrations
{
    [DbContext(typeof(HarmonIQDbContext))]
    [Migration("20260811203419_V2Initial")]
    partial class V2Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("HarmonIQ.Api.Models.Analysis", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CohortEvidencePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("CohortOrientationPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ElementBalanceJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<double?>("InteriorsCoverage")
                        .HasColumnType("REAL");

                    b.Property<int?>("InteriorsScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("NumerologyAdjustment")
                        .HasColumnType("REAL");

                    b.Property<string>("PrincipleSet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportSha256")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportUri")
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SiteCoverage")
                        .HasColumnType("REAL");

                    b.Property<int?>("SiteScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "PrincipleSet", "RulesVersion")
                        .IsUnique();

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("HarmonIQ.Api.Models.EngineVersion", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalibrationJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesVersionFengshui")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesVersionVastu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Version");

                    b.ToTable("EngineVersions");
                });

            modelBuilder.Entity("HarmonIQ.Api.Models.InputSet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceHashesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidencePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumbersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrientationJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InputFingerprint");

                    b.HasIndex("SubjectId");

                    b.ToTable("InputSets");
                });

            modelBuilder.Entity("HarmonIQ.Api.Models.Observation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSetId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "EvidenceHash", "PromptVersion", "ModelId")
                        .IsUnique();

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("HarmonIQ.Api.Models.ProjectionRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cohort")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FloorPlanId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .HasColumnType("TEXT");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipleSet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ListingId", "FloorPlanId", "PrincipleSet");

                    b.ToTable("ProjectionRows");
                });

            modelBuilder.Entity("HarmonIQ.Api.Models.ScoringJob", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CostUsd")
                        .HasColumnType("REAL");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SubjectId", "EngineVersion");

                    b.ToTable("ScoringJobs");
                });

            modelBuilder.Entity("HarmonIQ.Api.Models.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Baths")
                        .HasColumnType("REAL");

                    b.Property<int?>("Beds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentSignature")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalPlanKey")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanImageHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SqftMax")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SqftMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPlanKey");

                    b.HasIndex("PropertyKey");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("HarmonIQ.Api.Models.SubjectOrientation", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cardinal")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<double?>("FacingDegrees")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SubjectId");

                    b.ToTable("SubjectOrientations");
                });
#pragma warning restore 612, 618
        }
    }
}
